export const SEARCH_FOCUS = "/HEADER/SEARCH_FOCUS";
export const SEARCH_BLUR = "/HEADER/SEARCH_BLUR";
export const SEARCH_MOUSE_ENTER = "/HEADER/SEARCH_MOUSE_ENTER";
export const SEARCH_MOUSE_LEAVE = "/HEADER/SEARCH_MOUSE_LEAVE";
export const GET_RECOMMEND_LIST = "/HEADER/GET_RECOMMEND_LIST";
export const SWITCH_LIST = "/HEADER/SWITCH_LIST";